########################################################################
 # Copyright (c) Intel Corporation 2023
 # SPDX-License-Identifier: BSD-3-Clause
########################################################################

version: '3.7'
networks:
  edgex-network:
    driver: bridge
services:
  file-sender-gateway:
    command: /as-file-sender-gateway -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - edgex-security-bootstrapper
      - edgex-core-consul
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      API_GATEWAY_HOST: edgex-kong
      API_GATEWAY_STATUS_PORT: '8100'
      EDGEX_SECURITY_SECRET_STORE: "true"
      MESSAGEQUEUE_HOST: edgex-redis
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      REGISTRY_HOST: edgex-core-consul
      SECRETSTORE_HOST: edgex-vault
      SECRETSTORE_PORT: '8200'
      SERVICE_HOST: file-sender-gateway
      SPIFFE_ENDPOINTSOCKET: /tmp/edgex/secrets/spiffe/public/api.sock
      SPIFFE_TRUSTBUNDLE_PATH: /tmp/edgex/secrets/spiffe/trust/bundle
      SPIFFE_TRUSTDOMAIN: edgexfoundry.org
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: '54321'
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: '6379'
      STAGEGATE_DATABASE_READYPORT: '6379'
      STAGEGATE_KONGDB_HOST: edgex-kong-db
      STAGEGATE_KONGDB_PORT: '5432'
      STAGEGATE_KONGDB_READYPORT: '54325'
      STAGEGATE_READY_TORUNPORT: '54329'
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: '8500'
      STAGEGATE_REGISTRY_READYPORT: '54324'
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: '54322'
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_AUTHMODE: usernamepassword
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_SECRETNAME: redisdb
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-redis
      APPLICATIONSETTINGS_JOBREPOHOST: job-repository
      APPLICATIONSETTINGS_TASKLAUNCHERHOST: task-launcher
      APPLICATIONSETTINGS_ARCHIVEFOLDER: /tmp/files/archive
      APPLICATIONSETTINGS_REJECTFOLDER: /tmp/files/reject
      WRITABLE_LOGLEVEL: DEBUG
    hostname: file-sender-gateway
    image: aicsd/as-file-sender-gateway:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:59786:59786/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - ${HOME}/data/gateway-files:/tmp/files
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-file-sender-gateway:/tmp/edgex/secrets/app-file-sender-gateway:ro,z
  task-launcher:
    command: /as-task-launcher -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - edgex-security-bootstrapper
      - edgex-core-consul
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      API_GATEWAY_HOST: edgex-kong
      API_GATEWAY_STATUS_PORT: '8100'
      DATABASE_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "true"
      MESSAGEQUEUE_HOST: edgex-redis
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      REGISTRY_HOST: edgex-core-consul
      SECRETSTORE_HOST: edgex-vault
      SECRETSTORE_PORT: '8200'
      SERVICE_HOST: task-launcher
      SPIFFE_ENDPOINTSOCKET: /tmp/edgex/secrets/spiffe/public/api.sock
      SPIFFE_TRUSTBUNDLE_PATH: /tmp/edgex/secrets/spiffe/trust/bundle
      SPIFFE_TRUSTDOMAIN: edgexfoundry.org
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: '54321'
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: '6379'
      STAGEGATE_DATABASE_READYPORT: '6379'
      STAGEGATE_KONGDB_HOST: edgex-kong-db
      STAGEGATE_KONGDB_PORT: '5432'
      STAGEGATE_KONGDB_READYPORT: '54325'
      STAGEGATE_READY_TORUNPORT: '54329'
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: '8500'
      STAGEGATE_REGISTRY_READYPORT: '54324'
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: '54322'
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_AUTHMODE: usernamepassword
      TRIGGER_EDGEXMESSAGEBUS_OPTIONAL_SECRETNAME: redisdb
      TRIGGER_EDGEXMESSAGEBUS_PUBLISHHOST_HOST: edgex-redis
      TRIGGER_EDGEXMESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-redis
      APPLICATIONSETTINGS_JOBREPOHOST: job-repository
      APPLICATIONSETTINGS_FILESENDERHOST: file-sender-gateway
      APPLICATIONSETTINGS_PIPELINESTATUSHOST: task-launcher
      APPLICATIONSETTINGS_REDISHOST: edgex-redis
      WRITABLE_LOGLEVEL: DEBUG
    hostname: task-launcher
    image: aicsd/as-task-launcher:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:59785:59785/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - ${HOME}/data/gateway-files:/tmp/files
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-task-launcher:/tmp/edgex/secrets/app-task-launcher:ro,z
  file-receiver-gateway:
    command: /ms-file-receiver-gateway -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - edgex-security-bootstrapper
      - edgex-core-consul
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      API_GATEWAY_HOST: edgex-kong
      API_GATEWAY_STATUS_PORT: '8100'
      EDGEX_SECURITY_SECRET_STORE: "true"
      MESSAGEQUEUE_HOST: edgex-redis
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      REGISTRY_HOST: edgex-core-consul
      SECRETSTORE_HOST: edgex-vault
      SECRETSTORE_PORT: '8200'
      SERVICE_HOST: file-receiver-gateway
      SPIFFE_ENDPOINTSOCKET: /tmp/edgex/secrets/spiffe/public/api.sock
      SPIFFE_TRUSTBUNDLE_PATH: /tmp/edgex/secrets/spiffe/trust/bundle
      SPIFFE_TRUSTDOMAIN: edgexfoundry.org
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: '54321'
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: '6379'
      STAGEGATE_DATABASE_READYPORT: '6379'
      STAGEGATE_KONGDB_HOST: edgex-kong-db
      STAGEGATE_KONGDB_PORT: '5432'
      STAGEGATE_KONGDB_READYPORT: '54325'
      STAGEGATE_READY_TORUNPORT: '54329'
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: '8500'
      STAGEGATE_REGISTRY_READYPORT: '54324'
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: '54322'
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      APPLICATIONSETTINGS_JOBREPOHOST: job-repository
      APPLICATIONSETTINGS_TASKLAUNCHERHOST: task-launcher
      APPLICATIONSETTINGS_BASEFILEFOLDER: /tmp/files/input
      WRITABLE_LOGLEVEL: DEBUG
    hostname: file-receiver-gateway
    image: aicsd/ms-file-receiver-gateway:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:59783:59783/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - ${HOME}/data/gateway-files:/tmp/files
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-file-receiver-gateway:/tmp/edgex/secrets/app-file-receiver-gateway:ro,z
  job-repository:
    command: /ms-job-repository -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - edgex-security-bootstrapper
      - edgex-core-consul
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      API_GATEWAY_HOST: edgex-kong
      API_GATEWAY_STATUS_PORT: '8100'
      DATABASE_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "true"
      MESSAGEQUEUE_HOST: edgex-redis
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      REGISTRY_HOST: edgex-core-consul
      SECRETSTORE_HOST: edgex-vault
      SECRETSTORE_PORT: '8200'
      SERVICE_HOST: job-repository
      SPIFFE_ENDPOINTSOCKET: /tmp/edgex/secrets/spiffe/public/api.sock
      SPIFFE_TRUSTBUNDLE_PATH: /tmp/edgex/secrets/spiffe/trust/bundle
      SPIFFE_TRUSTDOMAIN: edgexfoundry.org
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: '54321'
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: '6379'
      STAGEGATE_DATABASE_READYPORT: '6379'
      STAGEGATE_KONGDB_HOST: edgex-kong-db
      STAGEGATE_KONGDB_PORT: '5432'
      STAGEGATE_KONGDB_READYPORT: '54325'
      STAGEGATE_READY_TORUNPORT: '54329'
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: '8500'
      STAGEGATE_REGISTRY_READYPORT: '54324'
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: '54322'
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      APPLICATIONSETTINGS_REDISHOST: edgex-redis
      WRITABLE_LOGLEVEL: DEBUG
    hostname: job-repository
    image: aicsd/ms-job-repository:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:59784:59784/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-job-repository:/tmp/edgex/secrets/app-job-repository:ro,z
  web-ui:
    hostname: web-ui
    image: aicsd/ms-web-ui:0.0.0-dev
    ports:
      - 4200:80/tcp
    networks:
      edgex-network: {}
    restart: unless-stopped
    environment: 
      - JOB_API_URL=http://${GATEWAY_IP_ADDR}:59784/api/v1/job
      - TASK_API_URL=http://${GATEWAY_IP_ADDR}:59785/api/v1/task
      - PIPELINES_API_URL=http://${GATEWAY_IP_ADDR}:10107/api/v1/pipelines
      - MODEL_API_URL=http://${GATEWAY_IP_ADDR}:8080/upload
      - REJECT_API_URL=http://${GATEWAY_IP_ADDR}:59786/api/v1/reject
    volumes:
      - ${HOME}/data/gateway-files:/app/assets/tmp/files

