########################################################################
 # Copyright (c) Intel Corporation 2023
 # SPDX-License-Identifier: BSD-3-Clause
########################################################################

version: '3.7'
networks:
  edgex-network:
    driver: bridge
services:
  oem-ssh-proxy:
    build:
      context: edgex-res/oem-ssh-proxy
    command: docker-entrypoint.sh
    container_name: edgex-oem-ssh-proxy
    depends_on:
      - edgex-core-consul
      - edgex-security-bootstrapper
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SECRETSTORE_HOST: edgex-vault
      SECRETSTORE_PORT: '8200'
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_READY_TORUNPORT: '54329'
      STAGEGATE_WAITFOR_TIMEOUT: '60s'
      # Unique for ssh-proxy
      TUNNEL_HOST: <OEM_IP_ADDRESS>
      TUNNEL_SSH_PORT: 2223
      JOB_REPO_HOST: job-repository
      JOB_REPO_PORT: 59784
      FILE_SENDER_GATEWAY_HOST: file-sender-gateway
      FILE_SENDER_GATEWAY_PORT: 59786
      TASK_LAUNCHER_HOST: task-launcher
      TASK_LAUNCHER_PORT: 59785
      FILE_RECEIVER_GATEWAY_HOST: file-receiver-gateway
      FILE_RECEIVER_GATEWAY_PORT: 59783
      SECRETSTORE_RUNTIMETOKENPROVIDER_HOST: edgex-security-spiffe-token-provider
      SECRETSTORE_RUNTIMETOKENPROVIDER_PORT: 59841
      SECURITY_SPIRE_SERVER_HOST: edgex-security-spire-server
      SECURITY_SPIRE_SERVER_PORT: 59840
    hostname: edgex-oem-ssh-proxy
    image: oem-ssh-proxy:latest
    networks:
      edgex-network:
        aliases:
          - file-watcher
          - data-organizer
          - file-sender-oem
          - file-receiver-oem
    ports:
      - 127.0.0.1:59781:59781/tcp
      - 127.0.0.1:59782:59782/tcp
      - 127.0.0.1:59780:59780/tcp
      - 127.0.0.1:59787:59787/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
    volumes:
      - edgex-init:/edgex-init:ro,z
      - spire-ca:/srv/spiffe/ca:z
      - spire-remote-agent:/srv/spiffe/remote-agent:z
      - /tmp/edgex/secrets/spiffe/trust:/tmp/edgex/secrets/spiffe/trust:ro,z
      - $PWD/edgex-res/ssh_keys:/root/.ssh
  security-spiffe-token-provider:
    command:
      - /security-spiffe-token-provider
      - -cp=consul.http://edgex-core-consul:8500
    container_name: edgex-security-spiffe-token-provider
    depends_on:
      consul:
        condition: service_started
      security-bootstrapper:
        condition: service_started
      security-spire-agent:
        condition: service_started
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      SECRETSTORE_HOST: edgex-vault
      SERVICE_HOST: edgex-security-spiffe-token-provider
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
    hostname: edgex-security-spiffe-token-provider
    image: edgexfoundry/security-spiffe-token-provider:3.1.0
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59841
        published: "59841"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
    user: root:root
    volumes:
      - type: volume
        source: edgex-init
        target: /edgex-init
        volume: { }
      - type: bind
        source: /tmp/edgex/secrets/spiffe
        target: /tmp/edgex/secrets/spiffe
        bind:
          selinux: z
          create_host_path: true
      - type: bind
        source: /tmp/edgex/secrets/security-spiffe-token-provider
        target: /tmp/edgex/secrets/security-spiffe-token-provider
        bind:
          selinux: z
          create_host_path: true
  security-spire-agent:
    command:
      - docker-entrypoint.sh
    container_name: edgex-security-spire-agent
    depends_on:
      security-spire-server:
        condition: service_started
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      SECRETSTORE_HOST: edgex-vault
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
    hostname: edgex-security-spire-agent
    image: edgexfoundry/security-spire-agent:3.1.0
    networks:
      edgex-network: null
    pid: host
    privileged: true
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
    user: root:root
    volumes:
      - type: volume
        source: edgex-init
        target: /edgex-init
        volume: { }
      - type: volume
        source: spire-ca
        target: /srv/spiffe/ca
        volume: { }
      - type: volume
        source: spire-agent
        target: /srv/spiffe/agent
        volume: { }
      - type: bind
        source: /tmp/edgex/secrets/spiffe
        target: /tmp/edgex/secrets/spiffe
        bind:
          selinux: z
          create_host_path: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
  security-spire-config:
    command:
      - docker-entrypoint.sh
    container_name: edgex-security-spire-config
    depends_on:
      security-spire-agent:
        condition: service_started
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      SECRETSTORE_HOST: edgex-vault
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
    hostname: edgex-security-spire-config
    image: edgexfoundry/security-spire-config:3.1.0
    networks:
      edgex-network: null
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
    user: root:root
    volumes:
      - type: volume
        source: edgex-init
        target: /edgex-init
        volume: { }
      - type: bind
        source: /tmp/edgex/secrets/spiffe
        target: /tmp/edgex/secrets/spiffe
        bind:
          selinux: z
          create_host_path: true
  security-spire-server:
    command:
      - docker-entrypoint.sh
    container_name: edgex-security-spire-server
    depends_on:
      security-bootstrapper:
        condition: service_started
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      SECRETSTORE_HOST: edgex-vault
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
    hostname: edgex-security-spire-server
    image: edgexfoundry/security-spire-server:3.1.0
    networks:
      edgex-network: null
    pid: host
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 59840
        published: "59840"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run
    user: root:root
    volumes:
      - type: volume
        source: edgex-init
        target: /edgex-init
        volume: { }
      - type: volume
        source: spire-ca
        target: /srv/spiffe/ca
        volume: { }
      - type: volume
        source: spire-server
        target: /srv/spiffe/server
        volume: { }
      - type: bind
        source: /tmp/edgex/secrets/spiffe
        target: /tmp/edgex/secrets/spiffe
        bind:
          selinux: z
          create_host_path: true
volumes:
  spire-agent:
    name: edgex_spire-agent
  spire-remote-agent:
    name: edgex_spire-remote-agent
  spire-ca:
    name: edgex_spire-ca
  spire-server:
    name: edgex_spire-server