########################################################################
 # Copyright (c) Intel Corporation 2023
 # SPDX-License-Identifier: BSD-3-Clause
########################################################################

version: '3.7'
networks:
  edgex-network:
    driver: bridge
services:
  data-organizer:
    command: /ms-data-organizer -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - security-bootstrapper
      - consul
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      SECRETSTORE_HOST: edgex-vault
      SERVICE_HOST: data-organizer
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      APPLICATIONSETTINGS_JOBREPOHOST: job-repository
      APPLICATIONSETTINGS_TASKLAUNCHERHOST: task-launcher
      APPLICATIONSETTINGS_FILESENDERHOST: file-sender-oem
    image: aicsd/ms-data-organizer:0.0.0-dev
    networks:
      edgex-network: { }
    ports:
      - 127.0.0.1:59781:59781/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - ${HOME}/data/oem-files:/tmp/files
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-data-organizer:/tmp/edgex/secrets/app-data-organizer:ro,z
  file-sender-oem:
    command: /ms-file-sender-oem -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - security-bootstrapper
      - consul
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      SECRETSTORE_HOST: edgex-vault
      SERVICE_HOST: file-sender-oem
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      APPLICATIONSETTINGS_JOBREPOHOST: job-repository
      APPLICATIONSETTINGS_FILERECEIVERHOST: file-receiver-gateway
    image: aicsd/ms-file-sender-oem:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:59782:59782/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - ${HOME}/data/oem-files:/tmp/files
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-file-sender-oem:/tmp/edgex/secrets/app-file-sender-oem:ro,z
  file-watcher:
    command: /ms-file-watcher -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - security-bootstrapper
      - consul
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      SECRETSTORE_HOST: edgex-vault
      SERVICE_HOST: file-watcher
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      APPLICATIONSETTINGS_DATAORGHOST: data-organizer
      APPLICATIONSETTINGS_FOLDERSTOWATCH: /tmp/files/input
    image: aicsd/ms-file-watcher:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:59780:59780/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - ${HOME}/data/oem-files:/tmp/files
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-file-watcher:/tmp/edgex/secrets/app-file-watcher:ro,z
  file-receiver-oem:
    command: /as-file-receiver-oem -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res -s
    depends_on:
      - security-bootstrapper
      - consul
    entrypoint:
      - /edgex-init/ready_to_run_wait_install.sh
    environment:
      EDGEX_SECURITY_SECRET_STORE: "true"
      SECRETSTORE_HOST: edgex-vault
      SERVICE_HOST: file-receiver-oem
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
      APPLICATIONSETTINGS_JOBREPOHOST: job-repository
      APPLICATIONSETTINGS_FILESENDERHOST: file-sender-gateway
      APPLICATIONSETTINGS_OUTPUTFOLDER: /tmp/files/output
    image: aicsd/as-file-receiver-oem:0.0.0-dev
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:59787:59787/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    volumes:
      - ${HOME}/data/oem-files:/tmp/files
      - edgex-init:/edgex-init:z
      - /tmp/edgex/secrets/app-file-receiver-oem:/tmp/edgex/secrets/app-file-receiver-oem:ro,z