########################################################################
 # Copyright (c) Intel Corporation 2023
 # SPDX-License-Identifier: BSD-3-Clause
########################################################################

networks:
  monitoring:
  edgex-network:
    driver: bridge
volumes:
  grafana-volume:
  influxdb-volume:
services:
  grafana:
    image: aicsd/grafana:0.0.0-dev
    ports:
      - 3001:3001/tcp
    restart: always
    networks:
      edgex-network: {}
      monitoring: {}
    user: 2002:2001
    env_file:
      .env
    volumes:
      - /tmp:/tmp
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
  influxdb:
    image: influxdb:2.0.9
    ports:
      - 8086:8086/tcp
    restart: always
    networks:
      edgex-network: {}
      monitoring: {}
    volumes:
      - influxdb-volume:/var/lib/influxdb2:rw
    env_file:
      .env
  telegraf:
    image: telegraf:1.22.4
    depends_on:
      - influxdb
      - grafana
    restart: always
    networks:
      edgex-network: { }
      monitoring: { }
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    env_file:
      .env