[Writable]
LogLevel = "INFO"

  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
Port = 59785
ServerBindAddr = "" # Leave blank so default to Host value unless different value is needed.
StartupMsg = "Started the task launcher microservice"
MaxResultCount = 0 # Not currently used by App Services.
MaxRequestSize = 0 # Not currently used by App Services.
RequestTimeout = "15s"

  [Service.CORSConfiguration]
  EnableCORS = true
  CORSAllowCredentials = false
  CORSAllowedOrigin = "*"
  CORSAllowedMethods = "GET, POST, PUT, PATCH, DELETE"
  CORSAllowedHeaders = "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID, DNT, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control"
  CORSExposeHeaders = "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
  CORSMaxAge = 3600

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[Database]
Type = "redisdb"
Host = "localhost"
Port = 6379
Timeout = "30s"

[SecretStore]
Type = "vault"
Protocol = "http"
Host = "localhost"
Port = 8200
Path = "app-task-launcher/"
TokenFile = "/tmp/edgex/secrets/app-task-launcher/secrets-token.json"
RootCaCertPath = ""
ServerName = ""
[SecretStore.Authentication]
  AuthType = "X-Vault-Token"

[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "redis"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"
    SubscribeTopics="NONE" # This service only publishes to the MessageBus, but must have a subscription for the SDK
    [Trigger.EdgexMessageBus.PublishHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"
    PublishTopic="{publish-topic}"
    [Trigger.EdgexMessageBus.Optional]
    ClientId ="app-task-launcher"
    Qos            = "0" # Quality of Service values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive      = "10" # Seconds (must be 2 or greater)
    Retained       = "false"
    AutoReconnect  = "true"
    ConnectTimeout = "15" # Seconds
    SkipCertVerify = "false"
    authmode = "usernamepassword"  # change to "usernamepassword", "clientcert", or "cacert" for secure MQTT messagebus.
    secretname = "redisdb"
    # Default NATS Specific options that need to be here to enable environment variable overrides of them
    Format = "nats"
    RetryOnFailedConnect = "true"
    QueueGroup = ""
    Durable = ""
    AutoProvision = "true"
    Deliver = "new"
    DefaultPubRetryAttempts = "2"
    Subject = "edgex/#" # Required for NATS JetStream only for stream autoprovisioning

[ApplicationSettings]
JobRepoHost="localhost"
JobRepoPort="59784"

FileSenderHost="localhost"
FileSenderPort="59786"

# This is same as in Service section above, but SDk doesn't expose them to be used.
PipelineStatusHost="localhost"
PipelineStatusPort="59785"

# Used for the ResourceName of the Event/Reading  that is published to launch the pipeline
ResourceName = "PipelineParameters"

DeviceProfileName = "ValitaCell"
# This will match the OEM equipment name in the File Watcher for now,
# It is needed  before we receive any files.
DeviceName = "Device1"

# Used for retry logic
RetryWindow="24h"

RedisHost = "localhost"
RedisPort = "6379"

FileHostname="gateway"

LocalizationFiles="./res/dictionary.en.json,./res/dictionary.zh.json"