[Writable]
LogLevel = "INFO"

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
Port = 59781
ServerBindAddr = "" # if blank, uses default Go behavior https://golang.org/pkg/net/#Listen
StartupMsg = "Started the data organizer microservice"
RequestTimeout = "15s"
MaxRequestSize = 0
MaxResultCount = 0

  [Service.CORSConfiguration]
  EnableCORS = false
  CORSAllowCredentials = false
  CORSAllowedOrigin = "http://localhost"
  CORSAllowedMethods = "GET, POST, PUT, PATCH, DELETE"
  CORSAllowedHeaders = "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
  CORSExposeHeaders = "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
  CORSMaxAge = 3600

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[SecretStore]
Type = "vault"
Protocol = "http"
Host = "edgex-vault"
Port = 8200
Path = "app-data-organizer/"
TokenFile = "/tmp/edgex/secrets/app-data-organizer/secrets-token.json"
RootCaCertPath = ""
ServerName = ""
[SecretStore.Authentication]
  AuthType = "X-Vault-Token"
[SecretStore.RuntimeTokenProvider]
  Enabled = false
  Protocol = "https"
  Host = "localhost"
  Port = 59841
  TrustDomain = "edgexfoundry.org"
  EndpointSocket = "/tmp/edgex/secrets/spiffe/public/api.sock"
  RequiredSecrets = "redisdb"

[Trigger]
Type="http"

# App Service specific simple settings
# Great for single string settings. For more complex structured custom configuration
# See https://docs.edgexfoundry.org/2.0/microservices/application/AdvancedTopics/#custom-configuration
[ApplicationSettings]

JobRepoHost="localhost"
JobRepoPort="59784"

TaskLauncherHost="localhost"
TaskLauncherPort="59785"

FileSenderHost="localhost"
FileSenderPort="59782"

PrivateKeyPath=""
JWTKeyPath=""
JWTAlgorithm=""
JWTDuration=""

[AttributeParser]
  [AttributeParser.Name]
  Id="parserExampleId"
  DataType="int"