# INTEL CONFIDENTIAL

# Copyright (C) 2023 Intel Corporation

# This software and the related documents are Intel copyrighted materials, and your use of them is governed by the express
# license under which they were provided to you ("License"). Unless the License provides otherwise, you may not use, modify,
# copy, publish, distribute, disclose or transmit this software or the related documents without Intel's prior written permission.

# This software and the related documents are provided as is, with no express or implied warranties, other than those that are expressly stated in the License.

openapi: 3.0.3
info:
  title: File Receiver OEM APIs
  version: 1.0.0
servers:
  - url: https://localhost:59787/api/v1
paths:
  /retry:
    post:
      summary: retries all jobs owned by the file receiver OEM
      description: receives all job entries the file receiver on the OEM device owns and attempts to process them
      operationId: retry
      responses:
        '200':
          description: Successful operation
        '500':
          description: Failed to process job(s)
