[Writable]
LogLevel = "INFO"
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
        path = "redisdb"
        [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
Port = 59787
ServerBindAddr = "" # Leave blank so default to Host value unless different value is needed.
StartupMsg = "Started the file receiver OEM microservice"
MaxResultCount = 0 # Not currently used by App Services.
MaxRequestSize = 0 # Not currently used by App Services.
RequestTimeout = "60s"

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[SecretStore]
Type = "vault"
Protocol = "http"
Host = "edgex-vault"
Port = 8200
Path = "app-file-receiver-oem/"
TokenFile = "/tmp/edgex/secrets/app-file-receiver-oem/secrets-token.json"
RootCaCertPath = ""
ServerName = ""
[SecretStore.Authentication]
  AuthType = "X-Vault-Token"
[SecretStore.RuntimeTokenProvider]
  Enabled = false
  Protocol = "https"
  Host = "localhost"
  Port = 59841
  TrustDomain = "edgexfoundry.org"
  EndpointSocket = "/tmp/edgex/secrets/spiffe/public/api.sock"
  RequiredSecrets = "redisdb"

[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "redis"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 6379
    Protocol = "redis"
    SubscribeTopics="jobs"
    [Trigger.EdgexMessageBus.Optional]
    authmode = "usernamepassword"  # required for redis messagebus (secure or insecure).
    secretname = "redisdb"
    # Default MQTT Specific options that need to be here to enable environment variable overrides of them
    ClientId ="app-file-receiver-oem"
    Qos =  "0" # Quality of Service values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive =  "10" # Seconds (must be 2 or greater)
    Retained = "false"
    AutoReconnect = "true"
    ConnectTimeout = "15" # Seconds
    SkipCertVerify = "false"
    # Default NATS Specific options that need to be here to enable environment variable overrides of them
    Format = "nats"
    RetryOnFailedConnect = "true"
    QueueGroup = ""
    Durable = ""
    AutoProvision = "true"
    Deliver = "new"
    DefaultPubRetryAttempts = "2"
    Subject = "edgex/#" # Required for NATS JetStream only for stream autoprovisioning

[ApplicationSettings]
JobRepoHost="localhost"
JobRepoPort="59784"

FileSenderHost="localhost"
FileSenderPort="59786"

OutputFolder="/tmp/output"
FileHostname="oem"

PrivateKeyPath=""
JWTKeyPath=""
JWTAlgorithm=""
JWTDuration=""