// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	types "aicsd/pkg/types"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// HandleJob provides a mock function with given fields: entry
func (_m *Client) HandleJob(entry types.Job) error {
	ret := _m.Called(entry)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Job) error); ok {
		r0 = rf(entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
