// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "aicsd/pkg/types"
)

// Persistence is an autogenerated mock type for the Persistence type
type Persistence struct {
	mock.Mock
}

// Create provides a mock function with given fields: job
func (_m *Persistence) Create(job types.Job) (string, types.Job, error) {
	ret := _m.Called(job)

	var r0 string
	var r1 types.Job
	var r2 error
	if rf, ok := ret.Get(0).(func(types.Job) (string, types.Job, error)); ok {
		return rf(job)
	}
	if rf, ok := ret.Get(0).(func(types.Job) string); ok {
		r0 = rf(job)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(types.Job) types.Job); ok {
		r1 = rf(job)
	} else {
		r1 = ret.Get(1).(types.Job)
	}

	if rf, ok := ret.Get(2).(func(types.Job) error); ok {
		r2 = rf(job)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: id
func (_m *Persistence) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Disconnect provides a mock function with given fields:
func (_m *Persistence) Disconnect() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Persistence) GetAll() ([]types.Job, error) {
	ret := _m.Called()

	var r0 []types.Job
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Job, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Job); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Job)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Persistence) GetById(id string) (types.Job, error) {
	ret := _m.Called(id)

	var r0 types.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (types.Job, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) types.Job); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(types.Job)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByOwner provides a mock function with given fields: owner
func (_m *Persistence) GetByOwner(owner string) ([]types.Job, error) {
	ret := _m.Called(owner)

	var r0 []types.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]types.Job, error)); ok {
		return rf(owner)
	}
	if rf, ok := ret.Get(0).(func(string) []types.Job); ok {
		r0 = rf(owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, values
func (_m *Persistence) Update(id string, values map[string]interface{}) (types.Job, error) {
	ret := _m.Called(id, values)

	var r0 types.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) (types.Job, error)); ok {
		return rf(id, values)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) types.Job); ok {
		r0 = rf(id, values)
	} else {
		r0 = ret.Get(0).(types.Job)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]interface{}) error); ok {
		r1 = rf(id, values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPersistence interface {
	mock.TestingT
	Cleanup(func())
}

// NewPersistence creates a new instance of Persistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPersistence(t mockConstructorTestingTNewPersistence) *Persistence {
	mock := &Persistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
