name: Dependabot export
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  dependabot:
    runs-on: ubuntu-latest    
    steps:               
      - name: Dependabot Alert CSV Export
        uses: antoniomtz/dependabot-alert-export
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:        
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          org_name: 'intel'
          repo_name: 'AiCSD'
          csv_path: data/vulnerability.csv          
      - name: Upload Vulnerability report
        uses: actions/upload-artifact@v3
        with:
           name: vulnerability_report
           path: data/vulnerability.csv          