# This is a TOML config file for edgexsecurity service.

LogLevel = "DEBUG"
SNIS = [""]
# RequestTimeout for proxy-setup http client caller
RequestTimeout = 10
AccessTokenFile = "/tmp/edgex/secrets/consul-acl-token/mgmt_token.json"

[KongURL]
Server = "127.0.0.1"
AdminPort = 8001
AdminPortSSL = 8444
ApplicationPort = 8000
ApplicationPortSSL = 8443
StatusPort = 8100

[KongAuth]
Name = "jwt"
TokenTTL = 0
Resource = "coredata"
OutputPath = "accessToken.json"
JWTFile = "/tmp/edgex/secrets/security-proxy-setup/kong-admin-jwt"

[CORSConfiguration]
EnableCORS = false
CORSAllowCredentials = false
CORSAllowedOrigin = "https://localhost"
CORSAllowedMethods = "GET, POST, PUT, PATCH, DELETE"
CORSAllowedHeaders = "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
CORSExposeHeaders = "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
CORSMaxAge = 3600

[SecretStore]
Type = "vault"
Protocol = "http"
Host = "localhost"
Port = 8200
Path = "security-proxy-setup/"
TokenFile = "/tmp/edgex/secrets/security-proxy-setup/secrets-token.json"
RootCaCertPath = ""
ServerName = ""
  [SecretStore.Authentication]
  AuthType = "X-Vault-Token"
  [SecretStore.RuntimeTokenProvider]
  Enabled = false
  Protocol = "https"
  Host = "localhost"
  Port = 59841
  TrustDomain = "edgexfoundry.org"
  EndpointSocket = "/tmp/edgex/secrets/spiffe/public/api.sock"
  RequiredSecrets = "redisdb"

[Routes]

  [Routes.core-consul]
  Name = "consul"
  Protocol = "http"
  Host = "localhost"
  Port = 8500